### ISSUE TITLE
Typed text is not coming in text view

### ISSUE THREAD

**Issue by ShahnazK** [michaelprimez/revealedittext#1]
Hi, i just downloaded this library and trying to use. But after if i enter anything during edit mode, it doesn't add the text there. As initially my text is empty, it shows me 'Type...' during edit mode. It always shows that only irrespective of whatever i type. can you please help me?

**Comment by ShahnazK** [comment]
This issue is closed as i added 
`                android:focusable="true"
                android:focusableInTouchMode="true`
these two attributes to container LinearLayout. Sorry for opening this issues.

**Comment by michaelprimez** [comment]
No problem @ShahnazK , i just didn't had time to check it, thanks for using the library.

**Comment by behelit** [comment]
My linear layout doesn't have those but the text still doesn't appear (on Android Oreo 8.0)
