### ISSUE TITLE
RevealEditTextListener.onDoneEditPressed is not working

### ISSUE THREAD

**Issue by ShahnazK** [michaelprimez/revealedittext#2]
It seems there is no code written in `RevealEditText` class to invoke the listener. I added one line `           mRevealEditTextListener.onDoneEditPressed(mActualEditText.getText().toString());` in `onClick()` method in `else-if` part. I request if you can add that.

One more request, it doesn't reflect the edit text value as reveal text value. is it by design? I suggest if you can add that by default, will be really helpful.

**Comment by michaelprimez** [comment]
Hi @ShahnazK 
The new version 1.0.2 calls correctly the onDoneEditPressed. Please give it a try.
Thank you for using the library and for the feedback.
